version: "3.8"

services:
  order_db:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - payment_volume:/var/opt/mssql
    container_name: payment_db

    environment:
      SA_PASSWORD: "Superl33tpassw0rd!"
      ACCEPT_EULA: "Y"
    ports:
     - "1433:1433"

  orderapi:
    build:
      context: ./OrderAPI
      dockerfile: ./OrderAPI/Dockerfile
    ports:
    - "8008"
    depends_on:
      - order_db

  payment_db:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - order_volume:/var/opt/mssql
    container_name: order_db

    environment:
      SA_PASSWORD: "Superl33tpassw0rd!"
      ACCEPT_EULA: "Y"
    ports:
     - "1434:1434"

  paymentapi:
    build:
      context: ./PaymentAPI
      dockerfile: ./PaymentAPI/Dockerfile
    ports:
    - "8009"
    depends_on:
      - paynment_db

volumes:
  payment_volume:
  order_volume: