version: "3.8"

services:
  order_db:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - payment_volume:/var/opt/mssql
    container_name: payment_db

    environment:
      SA_PASSWORD: "Superl33tpassw0rd!"
      ACCEPT_EULA: "Y"
    ports:
     - "1433:1433"

volumes:
  payment_volume: